[project]
name = "shared"
version = "0.1.0"
description = "Shared library component"
requires-python = ">=3.12"
dependencies = [
    "pydantic",
    "typing-extensions",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
