[project]
name = "webapp"
version = "0.1.0"
description = "Web application component"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
